apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse
  name: reverse
spec:
  ports:
  - name: "reverse-service"
    port: 5000
    targetPort: 5000
    nodePort: 30008
  selector:
    app: reverse
  type: NodePort
