apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse-and-random
  name: reverse-and-random
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30007
  selector:
    app: reverse-and-random
  type: NodePort

